### ISSUE TITLE
全量同步有问题，无法同步，单节点到单节点

### ISSUE THREAD

**Issue by yikela1990** [970263611/redis-x#3]
配置文件：
```yml
redisx:
  from:
    redis:
      version: 3.2.9
    password: Yws@1990
    isCluster: false
    address:
      - 172.30.75.78:6379
  to:
    password: Yws@1990
    isCluster: false
    address:
      - 172.30.75.78:6390
  console:
    enable: true
    port: 9999
    timeout: 5000
  immediate:
    enable: false
    resendTimes: 3
  alwaysFullSync: true
  switchFlag: REDIS-X-AUTHOR:DAHUA&CHANGDONGLIANG&ZHANGHUIHAO&ZHANGSHUHAN
```

``` sh
源端：

# Keyspace
db0:keys=450000,expires=450000,avg_ttl=6758415

127.0.0.1:6379> info memory
# Memory
used_memory:630731312
used_memory_human:601.51M



开启同步后日志无报错，但是等了很久，目标端只有一个key:
目标端：
127.0.0.1:6390> info memory
# Memory
used_memory:101565800
used_memory_human:96.86M

# Keyspace
db0:keys=1,expires=0,avg_ttl=0


源端redis log:
7871:M 01 Jul 16:20:34.467 * Starting BGSAVE for SYNC with target: disk
27871:M 01 Jul 16:20:34.489 * Background saving started by pid 13724
27871:M 01 Jul 16:20:36.449 * Slave 172.30.75.76:40466 asks for synchronization
27871:M 01 Jul 16:20:36.450 * Waiting for end of BGSAVE for SYNC
13724:C 01 Jul 16:20:42.863 * DB saved on disk
13724:C 01 Jul 16:20:42.891 * RDB: 2 MB of memory used by copy-on-write
27871:M 01 Jul 16:20:42.938 * Background saving terminated with success
27871:M 01 Jul 16:21:27.146 * Synchronization with slave 172.30.75.76:40464 succeeded
27871:M 01 Jul 16:21:28.722 * Synchronization with slave 172.30.75.76:40466 succeede


```
